#!/data/data/com.termux/files/usr/bin/sh

# Create a file for DISPLAY number. Users can do something like
# export DISPLAY=":$(cat $PREFIX/var/run/tx11-xfce4.display)"
# to use it.
exec 3<> /data/data/com.termux/files/usr/var/run/tx11-xfce4.display
exec termux-x11 -displayfd 3 -xstartup "dbus-launch --exit-with-session xfce4-session" 2>&1
